project:
  type: website

website:
  navbar:
    title: "WeatherXplore"
    right:
      - href: overview.qmd
        text: Overview
      - href: "https://weatherxplore.shinyapps.io/weatherxplore/"
        text: Shiny App
      - text: "Project Proposal"
        menu:
        - href: proposal_old.qmd
          text: Proposal (old)
        - href: proposal.qmd
          text: Proposal (revised)
      - text: "Prototype"
        menu:
        - href: data_prep.qmd
          text: Data Preparation
        - href: "https://isss608-priya.netlify.app/take-home_ex/take-home_ex03/take-home_ex03"
          text: Exploratory & Confirmatory Analytics
        - href: "https://isss608-ppthaw.netlify.app/take-home_ex/take-home_ex3/take-home_ex3"
          text: Time-series Analytics
        - href: "https://isss608-kenyongky.netlify.app/take-home_ex/take-home_ex03/take-home_ex03"
          text: Geospatial Analytics
      - href: team.qmd
        text: Our Team
    

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

