project:
  type: website

website:
  title: "WeatherXplore"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: proposal.qmd
        text: Project Proposal
      - about.qmd
    

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

