project:
  type: website

website:
  title: "WeatherXplore"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Project Proposal"
        menu:
        - href: proposal_old.qmd
          text: Proposal (old)
        - href: proposal.qmd
          text: Proposal (revised)
      - text: "Prototype"
        menu:
        - href: data_prep.qmd
          text: Data Preparation
        - href: "https://isss608-kenyongky.netlify.app/take-home_ex/take-home_ex03/take-home_ex03"
          text: Geospatial Analytics
      - about.qmd
    

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

