project:
  type: website

website:
  title: "WeatherXplore"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Project Proposal"
        menu:
        - href: proposal_old.qmd
          text: Proposal (old)
        - href: proposal.qmd
          text: Proposal (revised)
      - about.qmd
    

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

